In [63]:
from selenium import webdriver
import time
import pandas as pd
from math import ceil
import csv
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

## library untuk preprocessing teks
import csv 
import re 
import nltk
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize , sent_tokenize 
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

plt.style.use('ggplot')
sns.set_style('whitegrid')

In [64]:
data=[]

with Chrome(executable_path=r'C:\Program Files\chromedriver.exe') as driver:
    wait = WebDriverWait(driver,15)
    driver.get("https://www.youtube.com/watch?v=Jz2jprGz4Ag&feature=youtu.be")

    for item in range(200): 
        wait.until(EC.visibility_of_element_located((By.TAG_NAME, "body"))).send_keys(Keys.END)
        time.sleep(15)

    for comment in wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "#content-text"))):
        data.append(comment.text)

In [145]:
df = pd.DataFrame(data, columns=['comment'])
df

                                                                                                                                comment
0     HP semahal apa pun klo mau internetan tetap bayar pake kuota
1     8:01 sapa tuhh caper bgt wkkk
2     0:20 😂😂😂😂
3     10:37
4     0:19 anjirr ngakak 🤣
...                    ...
1567  Bang David :  "Ini kalo jatoh gak bakal pecah berarti soalnya ini plastik"\nMba"nya : "ya jangan di jatohin" \n\nMantull yaah 😂😂😂
1568  Kesannya jadi ribet
1569  Produk baru, kita masih belum tau seberapa lama tahan layarnya dibuka tutup, harganya mahal lagi.
1570  gua  malah ga suka hp yang ribet² kek gt wkwkw mungkin karena terbiasa dgn jiwa missqueen T_T
1571  Dfnbv v vvvccddfdc  c  cxxcccvxďpi7aa1asdģvbggğ bhvzfz\nXx\nĢbHc cc        vygtpooKSOSJAPĹLKPp

[1572 rows x 1 columns]

In [146]:
df.to_csv(r'D:\phytonwork\output_scrap_gadgetin37jt', index = False)

In [147]:
df

                                                                                                                                comment
0     HP semahal apa pun klo mau internetan tetap bayar pake kuota
1     8:01 sapa tuhh caper bgt wkkk
2     0:20 😂😂😂😂
3     10:37
4     0:19 anjirr ngakak 🤣
...                    ...
1567  Bang David :  "Ini kalo jatoh gak bakal pecah berarti soalnya ini plastik"\nMba"nya : "ya jangan di jatohin" \n\nMantull yaah 😂😂😂
1568  Kesannya jadi ribet
1569  Produk baru, kita masih belum tau seberapa lama tahan layarnya dibuka tutup, harganya mahal lagi.
1570  gua  malah ga suka hp yang ribet² kek gt wkwkw mungkin karena terbiasa dgn jiwa missqueen T_T
1571  Dfnbv v vvvccddfdc  c  cxxcccvxďpi7aa1asdģvbggğ bhvzfz\nXx\nĢbHc cc        vygtpooKSOSJAPĹLKPp

[1572 rows x 1 columns]

In [148]:
def clean_text(text):
  text=text.lower()
  text=re.sub("@[^\s]+", "", text)
  text=re.sub("\w*\d\w", "", text)
  text=re.sub(r'\w+:\/{2}[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*', "", text)
  text=re.sub(r'(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\S', "", text)
  text=re.sub("#[^\s]+", "", text)
  text=re.sub(r'\b[a-zA-Z]\b', "", text)
  return text

clean = lambda x: clean_text(x)

In [150]:
dfx=pd.DataFrame(df.comment.apply(clean))
dfx

                                                                                                                                comment
0     hp semahal apa pun klo mau internetan tetap bayar pake kuota
1     8: sapa tuhh caper bgt wkkk
2     0: 😂😂😂😂
3     :
4     0: anjirr ngakak 🤣
...                  ...
1567  bang david :  "ini kalo jatoh gak bakal pecah berarti soalnya ini plastik"\nmba"nya : "ya jangan di jatohin" \n\nmantull yaah 😂😂😂
1568  kesannya jadi ribet
1569  produk baru, kita masih belum tau seberapa lama tahan layarnya dibuka tutup, harganya mahal lagi.
1570  gua  malah ga suka hp yang ribet² kek gt wkwkw mungkin karena terbiasa dgn jiwa missqueen t_t
1571  dfnbv  vvvccddfdc    sdģvbggğ bhvzfz\nxx\nģbhc cc        vygtpooksosjapĺlkpp

[1572 rows x 1 columns]

In [152]:
def Punctuation(string):
  punctuation='''!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~'''
  for x in string.lower():
    if x in punctuation:
      string = string.replace(x, "")

  return(string)

cleanPunc = lambda x: Punctuation(x)

In [153]:
dfx=pd.DataFrame(df.comment.apply(cleanPunc))
dfx

                                                                                                                         comment
0     HP semahal apa pun klo mau internetan tetap bayar pake kuota
1     801 sapa tuhh caper bgt wkkk
2     020 😂😂😂😂
3     1037
4     019 anjirr ngakak 🤣
...                   ...
1567  Bang David   Ini kalo jatoh gak bakal pecah berarti soalnya ini plastik\nMbanya  ya jangan di jatohin \n\nMantull yaah 😂😂😂
1568  Kesannya jadi ribet
1569  Produk baru kita masih belum tau seberapa lama tahan layarnya dibuka tutup harganya mahal lagi
1570  gua  malah ga suka hp yang ribet² kek gt wkwkw mungkin karena terbiasa dgn jiwa missqueen TT
1571  Dfnbv v vvvccddfdc  c  cxxcccvxďpi7aa1asdģvbggğ bhvzfz\nXx\nĢbHc cc        vygtpooKSOSJAPĹLKPp

[1572 rows x 1 columns]

In [154]:
def get_stopword(stopwordsfile):
  stopwords=[]
  file_stopwords=open(stopwordsfile, 'r')
  row= file_stopwords.readline()
  while row:
    word=row.strip()
    stopwords.append(word)
    row=file_stopwords.readline()
  file_stopwords.close()
  return stopwords

In [169]:
stop_words_indo=get_stopword("D:/phytonwork/stopwordsindo.txt")

In [170]:
def stopwords(text):
  tokens = word_tokenize(text)
  filtered = []

  for w in tokens:
    if w not in stop_words_indo:
      filtered.append(w)

  hasil=' '.join(filtered)
  return hasil

st=lambda x: stopwords(x)

In [174]:
dfx = pd.DataFrame(dfx.comment.apply(cleanPunc))
dfx.head()

                                                        comment
0  HP semahal apa pun klo mau internetan tetap bayar pake kuota
1  801 sapa tuhh caper bgt wkkk
2  020 😂😂😂😂
3  1037
4  019 anjirr ngakak 🤣

In [177]:
def stemming(text):
  factory_stem=StemmerFactory()
  stemmer=factory_stem.create_stemmer()
  text=stemmer.stem(text)
  return text

stem = lambda x: stemming(x)

In [179]:
dfx = pd.DataFrame(dfx.comment.apply(stem))
dfx.head()

                                                      comment
0  hp mahal apa pun klo mau internetan tetap bayar pake kuota
1  801 sapa tuhh caper bgt wkkk
2  020
3  1037
4  019 anjirr ngakak

In [180]:
dfx["sentiment"]=df["sentiment"]
dfx

KeyError: 'sentiment'